COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:concurrent-trees',
    '//lib:jersey-client',
    '//lib:javax.ws.rs-api',
    '//utils/rest:onlab-rest',
    '//incubator/api:onos-incubator-api',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/intentsync:onos-apps-intentsync',
    '//lib:org.apache.karaf.shell.console',
    '//core/store/serializers:onos-core-serializers'
    '//cli:onos-cli'
]

BUNDLES = [
    '//apps/sdnip:onos-apps-sdnip',
    '//apps/routing-api:onos-apps-routing-api',
    '//apps/routing/common:onos-apps-routing-common',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//incubator/api:onos-incubator-api-tests',
    '//apps/routing-api:onos-apps-routing-api-tests',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
)

onos_app (
  title = 'Simple Leaf-Spine Network App',
  category = 'Traffic Steering',
  url = 'http://1.235.191.97/onos/slsnet',
  included_bundles = BUNDLES,
  description = 'Simple Leaf-Spine Network application',
  required_apps = [ 'org.onosproject.intentsynchronizer' ],
)
